// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgDAxingPJit1xNiJz2kC7UaPhorFgsy0',
    appId: '1:184475340418:web:9f1eb32af8bbc493ec6e9b',
    messagingSenderId: '184475340418',
    projectId: 'xeno-crm-app',
    authDomain: 'xeno-crm-app.firebaseapp.com',
    storageBucket: 'xeno-crm-app.appspot.com',
    measurementId: 'G-2GTZ2MBK1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwJtCD3z7RhKoKWjiFmO-NhV-Ys-kUUgk',
    appId: '1:184475340418:android:c317b2fe056cf99fec6e9b',
    messagingSenderId: '184475340418',
    projectId: 'xeno-crm-app',
    storageBucket: 'xeno-crm-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ4biHgsWBTwu2GfbOgjCbOKByQUSNHKg',
    appId: '1:184475340418:ios:a0cde9747b3fbd5bec6e9b',
    messagingSenderId: '184475340418',
    projectId: 'xeno-crm-app',
    storageBucket: 'xeno-crm-app.appspot.com',
    iosClientId: '184475340418-2lietj5mf4apcjev1isae0oum9aqbl1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.xenoCrrmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ4biHgsWBTwu2GfbOgjCbOKByQUSNHKg',
    appId: '1:184475340418:ios:a0cde9747b3fbd5bec6e9b',
    messagingSenderId: '184475340418',
    projectId: 'xeno-crm-app',
    storageBucket: 'xeno-crm-app.appspot.com',
    iosClientId: '184475340418-2lietj5mf4apcjev1isae0oum9aqbl1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.xenoCrrmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgDAxingPJit1xNiJz2kC7UaPhorFgsy0',
    appId: '1:184475340418:web:f3beadd57a7c5728ec6e9b',
    messagingSenderId: '184475340418',
    projectId: 'xeno-crm-app',
    authDomain: 'xeno-crm-app.firebaseapp.com',
    storageBucket: 'xeno-crm-app.appspot.com',
    measurementId: 'G-K3XNDJD5HZ',
  );

}